### PR TITLE
Add wzshiming as a reviewer

### PR DESCRIPTION
**Pull request by wzshiming**
I am a maintainer of [KWOK](https://github.com/kubernetes-sigs/kwok/), which simulates a k8s cluster. in many cases, direct manipulation of etcd would be helpful to simulate edge cases.

I would like to help improve this repo.

#3

### CODE REVIEW

**Review by jmhbnz — COMMENTED** [review]
Hi @wzshiming - Thanks for volunteering and for your contributions so far to auger!: https://github.com/search?q=org%3Aetcd-io+author%3Awzshiming+is%3Amerged&type=pullrequests

The first step for becoming a Reviewer is to become an `etcd-io` project Member, please refer to: https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/community-membership.md 

I am happy to sponsor you to become a Member. Once you have a second sponsor please open a [membership nomination](https://github.com/kubernetes/org/issues/new?assignees=&labels=area%2Fgithub-membership&projects=&template=membership.yml&title=REQUEST%3A+New+membership+for+%3Cyour-GH-handle%3E) issue against the kubernetes/org repo 🙏🏻 

I will close this pr as you need to first become and org Member and contribute to the project further as a Member before Reviewer role would be granted.

**Comment by wzshiming** [comment]
https://github.com/kubernetes/org/pull/4945
> The org memberships are now equivalent and sponsorship is not needed to join additional Kubernetes GitHub orgs. 

I found out that etcd-io and kubernetes membership are equivalent. 😄

**Comment by wzshiming** [comment]
Of course, although the budget of time I can spend here isn't what it used to be

**Comment by hwdef** [comment]
> Of course, although the budget of time I can spend here isn't what it used to be

Never mind, You have made many contributions before. You still have a few pending PRs; it would be even better if you could further develop them. :)

Perhaps you could create an issue first and apply to become a reviewer?

**Pull request closed without merging**
